#!/usr/bin/env bash
#
# Builds, signs and verifies a release APK without Gradle.
#
#   resources  -> aapt2 compile + link      (res/ + assets/ + manifest)
#   R.java     -> ecj                       (the JRE we ship has no javac)
#   Kotlin     -> kotlinc                   (against android.jar, no JDK)
#   bytecode   -> d8                        (classes.dex, min API 26)
#   package    -> tools/pack-apk.py         (aligned, resources.arsc STORED)
#   sign       -> apksigner                 (v2 + v3)
#
# Output: M3E-Calc-<version>-release-signed.apk in the repository root and in
# build/outputs/apk/release/.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TC="${TOOLCHAIN_DIR:-${TMPDIR:-/tmp}/m3e-toolchain}"
APP="$ROOT/app/src/main"
BUILD="$ROOT/build"
OUT="$BUILD/outputs/apk/release"
KEYSTORE="${KEYSTORE:-$ROOT/keystore/release.jks}"
KEY_ALIAS="${KEY_ALIAS:-m3ecalc}"
KEY_STOREPASS="${KEY_STOREPASS:-m3ecalc123}"
KEY_KEYPASS="${KEY_KEYPASS:-m3ecalc123}"
MIN_SDK=26
TARGET_SDK=34

say() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }

[ -x "$TC/java/bin/java" ] || "$ROOT/tools/setup-toolchain.sh"
JAVA="$TC/java/bin/java"
AAPT2="$TC/bin/aapt2"
ANDROID_JAR="$TC/lib/android.jar"
STDLIB="$TC/kotlin/lib/kotlin-stdlib.jar"
ANNOTATIONS="$TC/kotlin/lib/annotations-13.0.jar"

# ------------------------------------------------------------------- version
VERSION_NAME="$(grep '^versionName=' "$ROOT/app/version.properties" | cut -d= -f2)"
VERSION_CODE="$(grep '^versionCode=' "$ROOT/app/version.properties" | cut -d= -f2)"
APK_NAME="M3E-Calc-${VERSION_NAME}-release-signed.apk"

say "version $VERSION_NAME ($VERSION_CODE)"

rm -rf "$BUILD/intermediates" "$BUILD/generated" "$OUT"
mkdir -p "$BUILD/intermediates" "$BUILD/generated/com/flexteam/m3ecalc" "$OUT"

cat > "$BUILD/generated/com/flexteam/m3ecalc/BuildInfo.kt" <<EOF
package com.flexteam.m3ecalc

/** Generated by tools/build-apk.sh from app/version.properties. Do not edit. */
object BuildInfo {
    const val VERSION_NAME = "$VERSION_NAME"
    const val VERSION_CODE = $VERSION_CODE
    const val BUILD_DATE = "$(date -u +%Y-%m-%d)"
    const val APPLICATION_ID = "com.flexteam.m3ecalc"
}
EOF

# ----------------------------------------------------------------- resources
say "compiling resources"
"$AAPT2" compile --dir "$APP/res" -o "$BUILD/intermediates/res.zip"

say "linking resources"
"$AAPT2" link \
  -o "$BUILD/intermediates/base.apk" \
  -I "$ANDROID_JAR" \
  --manifest "$APP/AndroidManifest.xml" \
  -A "$APP/assets" \
  -R "$BUILD/intermediates/res.zip" \
  --java "$BUILD/intermediates/gen" \
  --auto-add-overlay \
  --min-sdk-version "$MIN_SDK" \
  --target-sdk-version "$TARGET_SDK" \
  --version-code "$VERSION_CODE" \
  --version-name "$VERSION_NAME"

# -------------------------------------------------------------------- R.java
say "compiling R.java"
"$JAVA" -jar "$TC/lib/ecj.jar" \
  -source 1.8 -target 1.8 -nowarn -proc:none \
  -d "$BUILD/intermediates/rclass" \
  $(find "$BUILD/intermediates/gen" -name '*.java') 2>&1 | grep -v '^$' || true
[ -d "$BUILD/intermediates/rclass" ] || { echo "R.java compilation failed" >&2; exit 1; }

# -------------------------------------------------------------------- Kotlin
say "compiling Kotlin sources"
SOURCES="$(find "$ROOT/app/src/main/kotlin" "$BUILD/generated" -name '*.kt')"
"$JAVA" -cp "$TC/kotlin/lib/kotlin-compiler.jar" \
  org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \
  -no-jdk -no-stdlib -jvm-target 1.8 \
  -classpath "$ANDROID_JAR:$STDLIB:$ANNOTATIONS:$BUILD/intermediates/rclass" \
  -d "$BUILD/intermediates/classes" \
  $SOURCES

# ----------------------------------------------------------------------- dex
say "dexing"
mkdir -p "$BUILD/intermediates/dex"
"$JAVA" -cp "$TC/lib/d8.jar" com.android.tools.r8.D8 \
  --lib "$ANDROID_JAR" \
  --min-api "$MIN_SDK" \
  --release \
  --output "$BUILD/intermediates/dex" \
  $(find "$BUILD/intermediates/classes" "$BUILD/intermediates/rclass" -name '*.class') \
  "$STDLIB" 2>&1 | grep -vE '^(Warning|warning):' || true
[ -f "$BUILD/intermediates/dex/classes.dex" ] || { echo "dexing failed" >&2; exit 1; }

# ------------------------------------------------------------------- package
say "packaging"
python3 "$ROOT/tools/pack-apk.py" \
  "$BUILD/intermediates/base.apk" \
  "$BUILD/intermediates/unaligned.apk" \
  "$BUILD/intermediates/dex/classes.dex"

# ---------------------------------------------------------------------- sign
say "signing"
[ -f "$KEYSTORE" ] || { echo "missing keystore: $KEYSTORE" >&2; exit 1; }
"$JAVA" -jar "$TC/lib/apksigner.jar" sign \
  --ks "$KEYSTORE" --ks-key-alias "$KEY_ALIAS" \
  --ks-pass "pass:$KEY_STOREPASS" --key-pass "pass:$KEY_KEYPASS" \
  --v1-signing-enabled false --v2-signing-enabled true --v3-signing-enabled true \
  --out "$OUT/$APK_NAME" \
  "$BUILD/intermediates/unaligned.apk"

say "verifying"
"$JAVA" -jar "$TC/lib/apksigner.jar" verify --verbose --print-certs "$OUT/$APK_NAME" 2>&1 \
  | grep -E 'Verified using|certificate DN|Number of signers'

cp "$OUT/$APK_NAME" "$ROOT/$APK_NAME"

say "done"
"$AAPT2" dump badging "$OUT/$APK_NAME" 2>/dev/null \
  | grep -E "^package|^launchable-activity|^application-label|sdkVersion|uses-permission" || true
ls -la "$ROOT/$APK_NAME"
